### ISSUE TITLE
Log.DEBUG = false 时候 启动报错

### ISSUE THREAD

**Issue by 157677678** [jerrylususu/apijson_todo_demo#1]
Log.DEBUG = true; 时候 能正常启动 也没有错误 但是改为 false时候  就会报错  得修改 
APIJSONApplication.init(false);

这个是设计就这样吗？ 还是有啥配置需要改？

**Comment by jerrylususu** [comment]
抱歉，在我的本地环境未能复现。如果在 DemoApplication 里取消 Log.Debug = false 的注释，需要在文件头部加入一行
```java
import apijson.Log;
```
加入后应该可以正常启动。如果有可能请在回复中详述具体的错误，还有你的 DemoApplication 的配置。此外我并不是 APIJSON 的官方开发者，如果未能解决你的问题，也欢迎向[官方项目](https://github.com/Tencent/APIJSON/issues)提 issue。

![image](https://user-images.githubusercontent.com/17522475/185943039-e01db7a7-f423-437d-b8d9-fd6bf3b96f5d.png)

**Comment by 157677678** [comment]
我的报错信息如下：

![QQ截图20220823101937](https://user-images.githubusercontent.com/67778969/186054586-c8d5ec6a-dca6-41f1-9285-b5123de2cd61.png)
 

改成true 就能通过 是不是咱俩包不一样 

我的 dependency：
```
dependencies {
    implementation 'com.github.APIJSON:apijson-framework:+'
    implementation 'com.github.APIJSON:APIJSON:+'

    implementation 'mysql:mysql-connector-java:8.0.27'

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

这个不一样吗？

**Comment by jerrylususu** [comment]
这是我一年之前的项目，最近没有太多时间更新维护。我本地的 APIJSON 版本是 ~~4.2.0~~（后来发现是 4.7.2），现在版本已经到了 5.2.0，可能是某个版本更新中引入了破坏性变更，导致表结构不一致了。这个问题可能需要等我之后有空再看了，如果你现在急需使用的话还请向官方的支持渠道寻求支持。

**Comment by TommyLemon** [comment]
> 这是我一年之前的项目，最近没有太多时间更新维护。我本地的 APIJSON 版本是 4.2.0，现在版本已经到了 5.2.0，可能是某个版本更新中引入了破坏性变更，导致表结构不一致了。这个问题可能需要等我之后有空再看了，如果你现在急需使用的话还请向官方的支持渠道寻求支持。

是这样。

@157677678 可以改用最新的 SQL 文件，或者自己加上 debug 字段
https://github.com/APIJSON/APIJSON-Demo/tree/master/MySQL

**Comment by jerrylususu** [comment]
已经升级本项目中的 APIJSON 依赖至 5.2.0，并增加数据库初始化 SQL 文件的 debug 列，初步自测问题已解决。具体变更见 https://github.com/jerrylususu/apijson_todo_demo/commit/8883f620576eaf97d61a0aab96c6b164acb0bae4 。

**Comment by 157677678** [comment]
感谢 没想到是数据库表不一致  辛苦您维护

**Comment by 157677678** [comment]
> > 这是我一年之前的项目，最近没有太多时间更新维护。我本地的 APIJSON 版本是 4.2.0，现在版本已经到了 5.2.0，可能是某个版本更新中引入了破坏性变更，导致表结构不一致了。这个问题可能需要等我之后有空再看了，如果你现在急需使用的话还请向官方的支持渠道寻求支持。
> 
> 是这样。
> 
> @157677678 可以改用最新的 SQL 文件，或者自己加上 debug 字段 https://github.com/APIJSON/APIJSON-Demo/tree/master/MySQL

感谢指点 ！
