### ISSUE TITLE
关于这个项目捐赠给 APIJSON Group

### ISSUE THREAD

**Issue by TommyLemon** [jerrylususu/apijson_todo_demo#2]
作者你好，我是 APIJSON 作者 Tommy，
收到了你在 8月27日 通过 Outlook 邮箱发来的邮件，
你提到因为工作忙碌时间精力不够，希望捐赠给 APIJSON Group 得到更好的维护。
我在 9月6 日看到并回复赞同以及可以参考的操作方法：
```
“感谢 Jerry 对 APIJSON 的贡献，
可以在 GitHub 这个项目的 Settings/General 底部 Transfer ownership，New owner 选 APIJSON”
```

后面一直没有得到你的回复，不知道是否因为已经主要改用贵公司的企业邮箱而未查看个人邮箱，
或者是因为网络或平台等问题导致没有收到等。

不涉及敏感的内容，我们也可以在 issue 中交流，感谢你对 APIJSON 的贡献，祝前程似锦~
https://github.com/Tencent/APIJSON/blob/master/CONTRIBUTING.md

**Comment by jerrylususu** [comment]
着实抱歉，之前因为一些原因没有及时关注到邮件回复。稍等我这边操作一下。

**Comment by jerrylususu** [comment]
提示报错"APIJSON/apijson_todo_demo already exists and You don’t have the permission to create public repositories on APIJSON "，可能是因为已经存在同名的 repo？可能需要麻烦您那边先移除，才能 transfer？

**Comment by TommyLemon** [comment]
已移除，可以再试试

**Comment by jerrylususu** [comment]
> 已移除，可以再试试

似乎还是有些问题，报错"You don’t have the permission to create public repositories on APIJSON  "。查了一下文档，看起来如果要把一个项目从个人账户转移到组织账户，需要原项目所有者在组织内有创建 repo 的权限。目前看来有两个做法：

1. 临时给我增加 APIJSON 的写权限，待转移完成后再撤销
2. 我先将这个项目转移至您的个人账户，然后您再转移到组织账户。

**Comment by TommyLemon** [comment]
已邀请为组织成员，可以通过邮件或 GitHub Notifications 接受加入 APIJSON Group 后再试试
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/5738175/198866833-ccf9c2dd-fea8-4cec-9066-3ff49a191466.png">

**Comment by jerrylususu** [comment]
感谢协助。迁移已完成。
